name: Crowdin Branch Clean-Up

on:
  pull_request:
      branches:
       - 'master*'
      types: [closed]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get PR closed number
        env:
          PR_NUMBER: ${{ toJson(github.event.number) }}
        run: |
          echo "$PR_NUMBER"
