name: Crowdin Branch Clean-Up

on:
  pull_request:
      branches:
       - 'master*'
      types: [closed]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Fetching Feature Branch
        run: |
          echo "Latest branch merged to master: ${{ steps.branch-name.outputs.head_ref_branch }}"
