name: Crowdin Branch Clean-Up

on:
    push:
        branches:
            - 'master-copy'
            

jobs:
    crowdin-branch-delete:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
            - name: Setup Node
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: '14.x'
            - run: npm i -g @crowdin/cli
            - run: npm ci
            - name: Git Setup
              run: 
                  echo "Setting up Git identity"
                  git config --global user.name "DerivFE"
                  git config --global user.email "80095553+DerivFE@users.noreply.github.com"
            - name: Delete Crowdin Branch 🗑️
              run: echo "Deleting"  
            - uses: tonynguyenit18/github-action-custom-vars@v1
            - run:  
                  crowdin branch delete -b $RECENT_MERGED_BRANCH_NAME -T ${{ secrets.CROWDIN_API_KEY }}
                    

        

     
