name: Pre-push Translation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
        - 'master*'
env: 
 BRANCH: github.head_ref
 CLEAN_BRANCH: "${BRANCH//[^[:alnum:]-_]/}"         
jobs:
    check-translation-branch:
        runs-on: ubuntu-latest
        if: startsWith(github.head_ref, 'translation') || startsWith(github.head_ref, 'stp')
        steps:
            - name: Branch Check 🔍 
              run: |
                echo '${{ env.CLEAN_BRANCH }} is a valid branch for translation workflow'

              
