name: Pre-push Translation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
        - 'master*'
env: 
 BRANCH: github.head_ref
 CLEAN_BRANCH: "${BRANCH//[^[:alnum:]-_]/}"         
jobs:
    check-translation-branch:
        runs-on: ubuntu-latest
        if: ${{ startsWith(env.CLEAN_BRANCH, 'translation') || startsWith(env.CLEAN_BRANCH, 'stp') }}
        steps:
            - name: Branch Check 🔍 
              run: |
                echo "$CLEAN_BRANCH is a valid branch for translation workflow"

              
