name: Pre-push Translation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
        - 'master*'
        
jobs:
    check-translation-branch:
        runs-on: ubuntu-latest
        steps:
          - uses: deepakputhraya/action-branch-name@master
            with:
              regex: '^[a-zA-Z0-9-_]+$' 
              allowed_prefixes: 'translation-,stp-' 
              ignore: master

